version: '3.7'
x-volumes:
  &default-volumes
  - ${EXTERNAL_FOLDER}/dp_logs:/logs
  - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
  - ${EXTERNAL_FOLDER}/tfhub:/tmp/tfhub

services:
  agent:
    build:
      context: ./
      dockerfile: dockerfile_agent
    container_name: agent
    depends_on:
    - odqa
    - chitchat
    - ner
    - sentiment
    - chitchat_odqa
    - mongo
    env_file: agent.env
    ports:
    - 4242:4242
    tty: true
    volumes:
    - .:/dp-agent
  chitchat:
    build:
      args:
        BASE_IMAGE: deeppavlov/base-cpu:0.6.1
        skillconfig: tfidf_autofaq
      context: ./
      dockerfile: dp/dockerfile_skill
    container_name: chitchat
    tty: true
    volumes: *default-volumes
  chitchat_odqa:
    build:
      args:
        BASE_IMAGE: deeppavlov/base-cpu:0.6.1
        skillconfig: rusentiment_bigru_superconv
      context: ./
      dockerfile: dp/dockerfile_skill
    container_name: chitchat_odqa
    tty: true
    volumes: *default-volumes
  mongo:
    command: mongod
    image: mongo:4.0.0
    ports:
    - 27017:27017
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/db:/root/data/db
  ner:
    build:
      args:
        BASE_IMAGE: deeppavlov/base-cpu:0.6.1
        skillconfig: ner_rus
      context: ./
      dockerfile: dp/dockerfile_skill
    container_name: ner
    tty: true
    volumes: *default-volumes
  odqa:
    build:
      args:
        BASE_IMAGE: deeppavlov/base-cpu:0.6.1
        skillconfig: ru_odqa_infer_wiki
      context: ./
      dockerfile: dp/dockerfile_skill
    container_name: odqa
    tty: true
    volumes: *default-volumes
  sentiment:
    build:
      args:
        BASE_IMAGE: deeppavlov/base-cpu:0.6.1
        skillconfig: rusentiment_cnn
      context: ./
      dockerfile: dp/dockerfile_skill
    container_name: sentiment
    tty: true
    volumes: *default-volumes
