services:
  agent:
    build:
      context: ..
      dockerfile: ../dockerfile_agent
    container_name: agent
    depends_on:
    - odqa
    - chitchat
    - ner
    - sentiment
    - chitchat_odqa
    - mongo
    ports:
    - 8888:8888
    tty: true
    volumes:
    - .:/dp-agent
  chitchat:
    build:
      args:
        gpu: 'false'
        skill_endpoint: model
        skillconfig: faq/tfidf_autofaq
        skillhost: 0.0.0.0
        skillport: 2081
      context: ..
      dockerfile: ../dockerfile_skill_basic
    container_name: chitchat
    environment:
    - CUDA_VISIBLE_DEVICES=""
    ports:
    - 2081:2081
    tty: true
    volumes:
    - .:/dp-agent
    - ${EXTERNAL_FOLDER}/dp_logs:/logs
    - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
  chitchat_odqa:
    build:
      args:
        gpu: 'false'
        skill_endpoint: intents
        skillconfig: classifiers/rusentiment_bigru_superconv
        skillhost: 0.0.0.0
        skillport: 2082
      context: ..
      dockerfile: ../dockerfile_skill_basic
    container_name: chitchat_odqa
    environment:
    - CUDA_VISIBLE_DEVICES=""
    ports:
    - 2082:2082
    tty: true
    volumes:
    - .:/dp-agent
    - ${EXTERNAL_FOLDER}/dp_logs:/logs
    - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
  mongo:
    command: mongod
    image: mongo:3.2.0
    ports:
    - 27017:27017
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ner:
    build:
      args:
        gpu: 'false'
        skill_endpoint: ner
        skillconfig: annotators/ner/preproc_ner_rus.json
        skillhost: 0.0.0.0
        skillport: 2083
      context: ..
      dockerfile: ../dockerfile_skill_basic
    container_name: ner
    environment:
    - CUDA_VISIBLE_DEVICES=""
    ports:
    - 2083:2083
    tty: true
    volumes:
    - .:/dp-agent
    - ${EXTERNAL_FOLDER}/dp_logs:/logs
    - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
  odqa:
    build:
      args:
        gpu: 'false'
        skill_endpoint: odqa
        skillconfig: skills/text_qa/agent_ru_odqa_retr_noans_rubert_infer.json
        skillhost: 0.0.0.0
        skillport: 2080
      context: ..
      dockerfile: ../dockerfile_skill_basic
    container_name: odqa
    environment:
    - CUDA_VISIBLE_DEVICES=""
    ports:
    - 2080:2080
    tty: true
    volumes:
    - .:/dp-agent
    - ${EXTERNAL_FOLDER}/dp_logs:/logs
    - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
  sentiment:
    build:
      args:
        gpu: 'false'
        skill_endpoint: intents
        skillconfig: classifiers/rusentiment_cnn
        skillhost: 0.0.0.0
        skillport: 2084
      context: ..
      dockerfile: ../dockerfile_skill_basic
    container_name: sentiment
    environment:
    - CUDA_VISIBLE_DEVICES=""
    ports:
    - 2084:2084
    tty: true
    volumes:
    - .:/dp-agent
    - ${EXTERNAL_FOLDER}/dp_logs:/logs
    - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
version: '2.3'
